#ifndef TARGET_OS_SIMULATOR
#include <TargetConditionals.h>
#endif
#if TARGET_OS_SIMULATOR
#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.2.4 effective-4.1.50 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Gridicons",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

enum GridiconType : NSInteger;
@class UIImage;

SWIFT_CLASS("_TtC9Gridicons8Gridicon")
@interface Gridicon : NSObject
///
/// returns:
/// A template image of the specified Gridicon type, at the default size.
+ (UIImage * _Nonnull)iconOfType:(enum GridiconType)type SWIFT_WARN_UNUSED_RESULT;
///
/// returns:
/// A template image of the specified Gridicon type, at the specified size.
+ (UIImage * _Nonnull)iconOfType:(enum GridiconType)type withSize:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, GridiconType, closed) {
  GridiconTypeVisible = 0,
  GridiconTypeVideoRemove = 1,
  GridiconTypeVideoCamera = 2,
  GridiconTypeVideo = 3,
  GridiconTypeUserCircle = 4,
  GridiconTypeUserAdd = 5,
  GridiconTypeUser = 6,
  GridiconTypeUndo = 7,
  GridiconTypeUnderline = 8,
  GridiconTypeTypes = 9,
  GridiconTypeTrophy = 10,
  GridiconTypeTrash = 11,
  GridiconTypeTime = 12,
  GridiconTypeThumbsUp = 13,
  GridiconTypeThemes = 14,
  GridiconTypeTextColor = 15,
  GridiconTypeTag = 16,
  GridiconTypeTablet = 17,
  GridiconTypeSync = 18,
  GridiconTypeStrikethrough = 19,
  GridiconTypeStatus = 20,
  GridiconTypeStatsAlt = 21,
  GridiconTypeStats = 22,
  GridiconTypeStarOutline = 23,
  GridiconTypeStar = 24,
  GridiconTypeSpecialCharacter = 25,
  GridiconTypeSpeaker = 26,
  GridiconTypeSpam = 27,
  GridiconTypeSignOut = 28,
  GridiconTypeShipping = 29,
  GridiconTypeShareIOS = 30,
  GridiconTypeShare = 31,
  GridiconTypeSearch = 32,
  GridiconTypeScheduled = 33,
  GridiconTypeRotate = 34,
  GridiconTypeResize = 35,
  GridiconTypeReply = 36,
  GridiconTypeRefund = 37,
  GridiconTypeRefresh = 38,
  GridiconTypeRedo = 39,
  GridiconTypeReblog = 40,
  GridiconTypeReaderFollowing = 41,
  GridiconTypeReaderFollow = 42,
  GridiconTypeReader = 43,
  GridiconTypeReadMore = 44,
  GridiconTypeQuote = 45,
  GridiconTypeProductVirtual = 46,
  GridiconTypeProductExternal = 47,
  GridiconTypeProductDownloadable = 48,
  GridiconTypeProduct = 49,
  GridiconTypePrint = 50,
  GridiconTypePosts = 51,
  GridiconTypePopout = 52,
  GridiconTypePlusSmall = 53,
  GridiconTypePlus = 54,
  GridiconTypePlugins = 55,
  GridiconTypePlay = 56,
  GridiconTypePlans = 57,
  GridiconTypePin = 58,
  GridiconTypePhone = 59,
  GridiconTypePencil = 60,
  GridiconTypePause = 61,
  GridiconTypePages = 62,
  GridiconTypeOffline = 63,
  GridiconTypeNoticeOutline = 64,
  GridiconTypeNotice = 65,
  GridiconTypeNotVisible = 66,
  GridiconTypeNextPage = 67,
  GridiconTypeMySitesHorizon = 68,
  GridiconTypeMySites = 69,
  GridiconTypeMultipleUsers = 70,
  GridiconTypeMoney = 71,
  GridiconTypeMinusSmall = 72,
  GridiconTypeMinus = 73,
  GridiconTypeMicrophone = 74,
  GridiconTypeMenus = 75,
  GridiconTypeMenu = 76,
  GridiconTypeMention = 77,
  GridiconTypeMail = 78,
  GridiconTypeLock = 79,
  GridiconTypeLocation = 80,
  GridiconTypeListUnordered = 81,
  GridiconTypeListOrdered = 82,
  GridiconTypeListOrderedRTL = 83,
  GridiconTypeListCheckmark = 84,
  GridiconTypeLinkBreak = 85,
  GridiconTypeLink = 86,
  GridiconTypeLayoutBlocks = 87,
  GridiconTypeLayout = 88,
  GridiconTypeItalic = 89,
  GridiconTypeInstitution = 90,
  GridiconTypeInk = 91,
  GridiconTypeInfoOutline = 92,
  GridiconTypeInfo = 93,
  GridiconTypeIndentRight = 94,
  GridiconTypeIndentLeft = 95,
  GridiconTypeImageRemove = 96,
  GridiconTypeImageMultiple = 97,
  GridiconTypeImage = 98,
  GridiconTypeHouse = 99,
  GridiconTypeHistory = 100,
  GridiconTypeHelpOutline = 101,
  GridiconTypeHelp = 102,
  GridiconTypeHeartOutline = 103,
  GridiconTypeHeart = 104,
  GridiconTypeHeadingH6 = 105,
  GridiconTypeHeadingH5 = 106,
  GridiconTypeHeadingH4 = 107,
  GridiconTypeHeadingH3 = 108,
  GridiconTypeHeadingH2 = 109,
  GridiconTypeHeadingH1 = 110,
  GridiconTypeHeading = 111,
  GridiconTypeGrid = 112,
  GridiconTypeGlobe = 113,
  GridiconTypeFullscreenExit = 114,
  GridiconTypeFullscreen = 115,
  GridiconTypeFolderMultiple = 116,
  GridiconTypeFolder = 117,
  GridiconTypeFlipVertical = 118,
  GridiconTypeFlipHorizontal = 119,
  GridiconTypeFlag = 120,
  GridiconTypeFilter = 121,
  GridiconTypeExternal = 122,
  GridiconTypeEllipsisCircle = 123,
  GridiconTypeEllipsis = 124,
  GridiconTypeDropdown = 125,
  GridiconTypeDomains = 126,
  GridiconTypeCustomize = 127,
  GridiconTypeCustomPostType = 128,
  GridiconTypeCrossSmall = 129,
  GridiconTypeCrossCircle = 130,
  GridiconTypeCross = 131,
  GridiconTypeCrop = 132,
  GridiconTypeCreditCard = 133,
  GridiconTypeCreate = 134,
  GridiconTypeCoupon = 135,
  GridiconTypeComputer = 136,
  GridiconTypeComment = 137,
  GridiconTypeCog = 138,
  GridiconTypeCode = 139,
  GridiconTypeCloudUpload = 140,
  GridiconTypeCloudOutline = 141,
  GridiconTypeCloudDownload = 142,
  GridiconTypeCloud = 143,
  GridiconTypeClipboard = 144,
  GridiconTypeClearFormatting = 145,
  GridiconTypeChevronUp = 146,
  GridiconTypeChevronRight = 147,
  GridiconTypeChevronLeft = 148,
  GridiconTypeChevronDown = 149,
  GridiconTypeCheckmarkCircle = 150,
  GridiconTypeCheckmark = 151,
  GridiconTypeChat = 152,
  GridiconTypeCart = 153,
  GridiconTypeCaption = 154,
  GridiconTypeCamera = 155,
  GridiconTypeCalendar = 156,
  GridiconTypeBug = 157,
  GridiconTypeBriefcase = 158,
  GridiconTypeBookmarkOutline = 159,
  GridiconTypeBookmark = 160,
  GridiconTypeBook = 161,
  GridiconTypeBold = 162,
  GridiconTypeBlock = 163,
  GridiconTypeBell = 164,
  GridiconTypeAudio = 165,
  GridiconTypeAttachment = 166,
  GridiconTypeAside = 167,
  GridiconTypeArrowUp = 168,
  GridiconTypeArrowRight = 169,
  GridiconTypeArrowLeft = 170,
  GridiconTypeArrowDown = 171,
  GridiconTypeAlignRight = 172,
  GridiconTypeAlignLeft = 173,
  GridiconTypeAlignJustify = 174,
  GridiconTypeAlignImageRight = 175,
  GridiconTypeAlignImageNone = 176,
  GridiconTypeAlignImageLeft = 177,
  GridiconTypeAlignImageCenter = 178,
  GridiconTypeAlignCenter = 179,
  GridiconTypeAddOutline = 180,
  GridiconTypeAddImage = 181,
  GridiconTypeAdd = 182,
};

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__i386__) && __i386__
// Generated by Apple Swift version 5.2.4 effective-4.1.50 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Gridicons",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

enum GridiconType : NSInteger;
@class UIImage;

SWIFT_CLASS("_TtC9Gridicons8Gridicon")
@interface Gridicon : NSObject
///
/// returns:
/// A template image of the specified Gridicon type, at the default size.
+ (UIImage * _Nonnull)iconOfType:(enum GridiconType)type SWIFT_WARN_UNUSED_RESULT;
///
/// returns:
/// A template image of the specified Gridicon type, at the specified size.
+ (UIImage * _Nonnull)iconOfType:(enum GridiconType)type withSize:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, GridiconType, closed) {
  GridiconTypeVisible = 0,
  GridiconTypeVideoRemove = 1,
  GridiconTypeVideoCamera = 2,
  GridiconTypeVideo = 3,
  GridiconTypeUserCircle = 4,
  GridiconTypeUserAdd = 5,
  GridiconTypeUser = 6,
  GridiconTypeUndo = 7,
  GridiconTypeUnderline = 8,
  GridiconTypeTypes = 9,
  GridiconTypeTrophy = 10,
  GridiconTypeTrash = 11,
  GridiconTypeTime = 12,
  GridiconTypeThumbsUp = 13,
  GridiconTypeThemes = 14,
  GridiconTypeTextColor = 15,
  GridiconTypeTag = 16,
  GridiconTypeTablet = 17,
  GridiconTypeSync = 18,
  GridiconTypeStrikethrough = 19,
  GridiconTypeStatus = 20,
  GridiconTypeStatsAlt = 21,
  GridiconTypeStats = 22,
  GridiconTypeStarOutline = 23,
  GridiconTypeStar = 24,
  GridiconTypeSpecialCharacter = 25,
  GridiconTypeSpeaker = 26,
  GridiconTypeSpam = 27,
  GridiconTypeSignOut = 28,
  GridiconTypeShipping = 29,
  GridiconTypeShareIOS = 30,
  GridiconTypeShare = 31,
  GridiconTypeSearch = 32,
  GridiconTypeScheduled = 33,
  GridiconTypeRotate = 34,
  GridiconTypeResize = 35,
  GridiconTypeReply = 36,
  GridiconTypeRefund = 37,
  GridiconTypeRefresh = 38,
  GridiconTypeRedo = 39,
  GridiconTypeReblog = 40,
  GridiconTypeReaderFollowing = 41,
  GridiconTypeReaderFollow = 42,
  GridiconTypeReader = 43,
  GridiconTypeReadMore = 44,
  GridiconTypeQuote = 45,
  GridiconTypeProductVirtual = 46,
  GridiconTypeProductExternal = 47,
  GridiconTypeProductDownloadable = 48,
  GridiconTypeProduct = 49,
  GridiconTypePrint = 50,
  GridiconTypePosts = 51,
  GridiconTypePopout = 52,
  GridiconTypePlusSmall = 53,
  GridiconTypePlus = 54,
  GridiconTypePlugins = 55,
  GridiconTypePlay = 56,
  GridiconTypePlans = 57,
  GridiconTypePin = 58,
  GridiconTypePhone = 59,
  GridiconTypePencil = 60,
  GridiconTypePause = 61,
  GridiconTypePages = 62,
  GridiconTypeOffline = 63,
  GridiconTypeNoticeOutline = 64,
  GridiconTypeNotice = 65,
  GridiconTypeNotVisible = 66,
  GridiconTypeNextPage = 67,
  GridiconTypeMySitesHorizon = 68,
  GridiconTypeMySites = 69,
  GridiconTypeMultipleUsers = 70,
  GridiconTypeMoney = 71,
  GridiconTypeMinusSmall = 72,
  GridiconTypeMinus = 73,
  GridiconTypeMicrophone = 74,
  GridiconTypeMenus = 75,
  GridiconTypeMenu = 76,
  GridiconTypeMention = 77,
  GridiconTypeMail = 78,
  GridiconTypeLock = 79,
  GridiconTypeLocation = 80,
  GridiconTypeListUnordered = 81,
  GridiconTypeListOrdered = 82,
  GridiconTypeListOrderedRTL = 83,
  GridiconTypeListCheckmark = 84,
  GridiconTypeLinkBreak = 85,
  GridiconTypeLink = 86,
  GridiconTypeLayoutBlocks = 87,
  GridiconTypeLayout = 88,
  GridiconTypeItalic = 89,
  GridiconTypeInstitution = 90,
  GridiconTypeInk = 91,
  GridiconTypeInfoOutline = 92,
  GridiconTypeInfo = 93,
  GridiconTypeIndentRight = 94,
  GridiconTypeIndentLeft = 95,
  GridiconTypeImageRemove = 96,
  GridiconTypeImageMultiple = 97,
  GridiconTypeImage = 98,
  GridiconTypeHouse = 99,
  GridiconTypeHistory = 100,
  GridiconTypeHelpOutline = 101,
  GridiconTypeHelp = 102,
  GridiconTypeHeartOutline = 103,
  GridiconTypeHeart = 104,
  GridiconTypeHeadingH6 = 105,
  GridiconTypeHeadingH5 = 106,
  GridiconTypeHeadingH4 = 107,
  GridiconTypeHeadingH3 = 108,
  GridiconTypeHeadingH2 = 109,
  GridiconTypeHeadingH1 = 110,
  GridiconTypeHeading = 111,
  GridiconTypeGrid = 112,
  GridiconTypeGlobe = 113,
  GridiconTypeFullscreenExit = 114,
  GridiconTypeFullscreen = 115,
  GridiconTypeFolderMultiple = 116,
  GridiconTypeFolder = 117,
  GridiconTypeFlipVertical = 118,
  GridiconTypeFlipHorizontal = 119,
  GridiconTypeFlag = 120,
  GridiconTypeFilter = 121,
  GridiconTypeExternal = 122,
  GridiconTypeEllipsisCircle = 123,
  GridiconTypeEllipsis = 124,
  GridiconTypeDropdown = 125,
  GridiconTypeDomains = 126,
  GridiconTypeCustomize = 127,
  GridiconTypeCustomPostType = 128,
  GridiconTypeCrossSmall = 129,
  GridiconTypeCrossCircle = 130,
  GridiconTypeCross = 131,
  GridiconTypeCrop = 132,
  GridiconTypeCreditCard = 133,
  GridiconTypeCreate = 134,
  GridiconTypeCoupon = 135,
  GridiconTypeComputer = 136,
  GridiconTypeComment = 137,
  GridiconTypeCog = 138,
  GridiconTypeCode = 139,
  GridiconTypeCloudUpload = 140,
  GridiconTypeCloudOutline = 141,
  GridiconTypeCloudDownload = 142,
  GridiconTypeCloud = 143,
  GridiconTypeClipboard = 144,
  GridiconTypeClearFormatting = 145,
  GridiconTypeChevronUp = 146,
  GridiconTypeChevronRight = 147,
  GridiconTypeChevronLeft = 148,
  GridiconTypeChevronDown = 149,
  GridiconTypeCheckmarkCircle = 150,
  GridiconTypeCheckmark = 151,
  GridiconTypeChat = 152,
  GridiconTypeCart = 153,
  GridiconTypeCaption = 154,
  GridiconTypeCamera = 155,
  GridiconTypeCalendar = 156,
  GridiconTypeBug = 157,
  GridiconTypeBriefcase = 158,
  GridiconTypeBookmarkOutline = 159,
  GridiconTypeBookmark = 160,
  GridiconTypeBook = 161,
  GridiconTypeBold = 162,
  GridiconTypeBlock = 163,
  GridiconTypeBell = 164,
  GridiconTypeAudio = 165,
  GridiconTypeAttachment = 166,
  GridiconTypeAside = 167,
  GridiconTypeArrowUp = 168,
  GridiconTypeArrowRight = 169,
  GridiconTypeArrowLeft = 170,
  GridiconTypeArrowDown = 171,
  GridiconTypeAlignRight = 172,
  GridiconTypeAlignLeft = 173,
  GridiconTypeAlignJustify = 174,
  GridiconTypeAlignImageRight = 175,
  GridiconTypeAlignImageNone = 176,
  GridiconTypeAlignImageLeft = 177,
  GridiconTypeAlignImageCenter = 178,
  GridiconTypeAlignCenter = 179,
  GridiconTypeAddOutline = 180,
  GridiconTypeAddImage = 181,
  GridiconTypeAdd = 182,
};

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif

#else
#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.2.4 effective-4.1.50 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Gridicons",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

enum GridiconType : NSInteger;
@class UIImage;

SWIFT_CLASS("_TtC9Gridicons8Gridicon")
@interface Gridicon : NSObject
///
/// returns:
/// A template image of the specified Gridicon type, at the default size.
+ (UIImage * _Nonnull)iconOfType:(enum GridiconType)type SWIFT_WARN_UNUSED_RESULT;
///
/// returns:
/// A template image of the specified Gridicon type, at the specified size.
+ (UIImage * _Nonnull)iconOfType:(enum GridiconType)type withSize:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, GridiconType, closed) {
  GridiconTypeVisible = 0,
  GridiconTypeVideoRemove = 1,
  GridiconTypeVideoCamera = 2,
  GridiconTypeVideo = 3,
  GridiconTypeUserCircle = 4,
  GridiconTypeUserAdd = 5,
  GridiconTypeUser = 6,
  GridiconTypeUndo = 7,
  GridiconTypeUnderline = 8,
  GridiconTypeTypes = 9,
  GridiconTypeTrophy = 10,
  GridiconTypeTrash = 11,
  GridiconTypeTime = 12,
  GridiconTypeThumbsUp = 13,
  GridiconTypeThemes = 14,
  GridiconTypeTextColor = 15,
  GridiconTypeTag = 16,
  GridiconTypeTablet = 17,
  GridiconTypeSync = 18,
  GridiconTypeStrikethrough = 19,
  GridiconTypeStatus = 20,
  GridiconTypeStatsAlt = 21,
  GridiconTypeStats = 22,
  GridiconTypeStarOutline = 23,
  GridiconTypeStar = 24,
  GridiconTypeSpecialCharacter = 25,
  GridiconTypeSpeaker = 26,
  GridiconTypeSpam = 27,
  GridiconTypeSignOut = 28,
  GridiconTypeShipping = 29,
  GridiconTypeShareIOS = 30,
  GridiconTypeShare = 31,
  GridiconTypeSearch = 32,
  GridiconTypeScheduled = 33,
  GridiconTypeRotate = 34,
  GridiconTypeResize = 35,
  GridiconTypeReply = 36,
  GridiconTypeRefund = 37,
  GridiconTypeRefresh = 38,
  GridiconTypeRedo = 39,
  GridiconTypeReblog = 40,
  GridiconTypeReaderFollowing = 41,
  GridiconTypeReaderFollow = 42,
  GridiconTypeReader = 43,
  GridiconTypeReadMore = 44,
  GridiconTypeQuote = 45,
  GridiconTypeProductVirtual = 46,
  GridiconTypeProductExternal = 47,
  GridiconTypeProductDownloadable = 48,
  GridiconTypeProduct = 49,
  GridiconTypePrint = 50,
  GridiconTypePosts = 51,
  GridiconTypePopout = 52,
  GridiconTypePlusSmall = 53,
  GridiconTypePlus = 54,
  GridiconTypePlugins = 55,
  GridiconTypePlay = 56,
  GridiconTypePlans = 57,
  GridiconTypePin = 58,
  GridiconTypePhone = 59,
  GridiconTypePencil = 60,
  GridiconTypePause = 61,
  GridiconTypePages = 62,
  GridiconTypeOffline = 63,
  GridiconTypeNoticeOutline = 64,
  GridiconTypeNotice = 65,
  GridiconTypeNotVisible = 66,
  GridiconTypeNextPage = 67,
  GridiconTypeMySitesHorizon = 68,
  GridiconTypeMySites = 69,
  GridiconTypeMultipleUsers = 70,
  GridiconTypeMoney = 71,
  GridiconTypeMinusSmall = 72,
  GridiconTypeMinus = 73,
  GridiconTypeMicrophone = 74,
  GridiconTypeMenus = 75,
  GridiconTypeMenu = 76,
  GridiconTypeMention = 77,
  GridiconTypeMail = 78,
  GridiconTypeLock = 79,
  GridiconTypeLocation = 80,
  GridiconTypeListUnordered = 81,
  GridiconTypeListOrdered = 82,
  GridiconTypeListOrderedRTL = 83,
  GridiconTypeListCheckmark = 84,
  GridiconTypeLinkBreak = 85,
  GridiconTypeLink = 86,
  GridiconTypeLayoutBlocks = 87,
  GridiconTypeLayout = 88,
  GridiconTypeItalic = 89,
  GridiconTypeInstitution = 90,
  GridiconTypeInk = 91,
  GridiconTypeInfoOutline = 92,
  GridiconTypeInfo = 93,
  GridiconTypeIndentRight = 94,
  GridiconTypeIndentLeft = 95,
  GridiconTypeImageRemove = 96,
  GridiconTypeImageMultiple = 97,
  GridiconTypeImage = 98,
  GridiconTypeHouse = 99,
  GridiconTypeHistory = 100,
  GridiconTypeHelpOutline = 101,
  GridiconTypeHelp = 102,
  GridiconTypeHeartOutline = 103,
  GridiconTypeHeart = 104,
  GridiconTypeHeadingH6 = 105,
  GridiconTypeHeadingH5 = 106,
  GridiconTypeHeadingH4 = 107,
  GridiconTypeHeadingH3 = 108,
  GridiconTypeHeadingH2 = 109,
  GridiconTypeHeadingH1 = 110,
  GridiconTypeHeading = 111,
  GridiconTypeGrid = 112,
  GridiconTypeGlobe = 113,
  GridiconTypeFullscreenExit = 114,
  GridiconTypeFullscreen = 115,
  GridiconTypeFolderMultiple = 116,
  GridiconTypeFolder = 117,
  GridiconTypeFlipVertical = 118,
  GridiconTypeFlipHorizontal = 119,
  GridiconTypeFlag = 120,
  GridiconTypeFilter = 121,
  GridiconTypeExternal = 122,
  GridiconTypeEllipsisCircle = 123,
  GridiconTypeEllipsis = 124,
  GridiconTypeDropdown = 125,
  GridiconTypeDomains = 126,
  GridiconTypeCustomize = 127,
  GridiconTypeCustomPostType = 128,
  GridiconTypeCrossSmall = 129,
  GridiconTypeCrossCircle = 130,
  GridiconTypeCross = 131,
  GridiconTypeCrop = 132,
  GridiconTypeCreditCard = 133,
  GridiconTypeCreate = 134,
  GridiconTypeCoupon = 135,
  GridiconTypeComputer = 136,
  GridiconTypeComment = 137,
  GridiconTypeCog = 138,
  GridiconTypeCode = 139,
  GridiconTypeCloudUpload = 140,
  GridiconTypeCloudOutline = 141,
  GridiconTypeCloudDownload = 142,
  GridiconTypeCloud = 143,
  GridiconTypeClipboard = 144,
  GridiconTypeClearFormatting = 145,
  GridiconTypeChevronUp = 146,
  GridiconTypeChevronRight = 147,
  GridiconTypeChevronLeft = 148,
  GridiconTypeChevronDown = 149,
  GridiconTypeCheckmarkCircle = 150,
  GridiconTypeCheckmark = 151,
  GridiconTypeChat = 152,
  GridiconTypeCart = 153,
  GridiconTypeCaption = 154,
  GridiconTypeCamera = 155,
  GridiconTypeCalendar = 156,
  GridiconTypeBug = 157,
  GridiconTypeBriefcase = 158,
  GridiconTypeBookmarkOutline = 159,
  GridiconTypeBookmark = 160,
  GridiconTypeBook = 161,
  GridiconTypeBold = 162,
  GridiconTypeBlock = 163,
  GridiconTypeBell = 164,
  GridiconTypeAudio = 165,
  GridiconTypeAttachment = 166,
  GridiconTypeAside = 167,
  GridiconTypeArrowUp = 168,
  GridiconTypeArrowRight = 169,
  GridiconTypeArrowLeft = 170,
  GridiconTypeArrowDown = 171,
  GridiconTypeAlignRight = 172,
  GridiconTypeAlignLeft = 173,
  GridiconTypeAlignJustify = 174,
  GridiconTypeAlignImageRight = 175,
  GridiconTypeAlignImageNone = 176,
  GridiconTypeAlignImageLeft = 177,
  GridiconTypeAlignImageCenter = 178,
  GridiconTypeAlignCenter = 179,
  GridiconTypeAddOutline = 180,
  GridiconTypeAddImage = 181,
  GridiconTypeAdd = 182,
};

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.2.4 effective-4.1.50 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Gridicons",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

enum GridiconType : NSInteger;
@class UIImage;

SWIFT_CLASS("_TtC9Gridicons8Gridicon")
@interface Gridicon : NSObject
///
/// returns:
/// A template image of the specified Gridicon type, at the default size.
+ (UIImage * _Nonnull)iconOfType:(enum GridiconType)type SWIFT_WARN_UNUSED_RESULT;
///
/// returns:
/// A template image of the specified Gridicon type, at the specified size.
+ (UIImage * _Nonnull)iconOfType:(enum GridiconType)type withSize:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, GridiconType, closed) {
  GridiconTypeVisible = 0,
  GridiconTypeVideoRemove = 1,
  GridiconTypeVideoCamera = 2,
  GridiconTypeVideo = 3,
  GridiconTypeUserCircle = 4,
  GridiconTypeUserAdd = 5,
  GridiconTypeUser = 6,
  GridiconTypeUndo = 7,
  GridiconTypeUnderline = 8,
  GridiconTypeTypes = 9,
  GridiconTypeTrophy = 10,
  GridiconTypeTrash = 11,
  GridiconTypeTime = 12,
  GridiconTypeThumbsUp = 13,
  GridiconTypeThemes = 14,
  GridiconTypeTextColor = 15,
  GridiconTypeTag = 16,
  GridiconTypeTablet = 17,
  GridiconTypeSync = 18,
  GridiconTypeStrikethrough = 19,
  GridiconTypeStatus = 20,
  GridiconTypeStatsAlt = 21,
  GridiconTypeStats = 22,
  GridiconTypeStarOutline = 23,
  GridiconTypeStar = 24,
  GridiconTypeSpecialCharacter = 25,
  GridiconTypeSpeaker = 26,
  GridiconTypeSpam = 27,
  GridiconTypeSignOut = 28,
  GridiconTypeShipping = 29,
  GridiconTypeShareIOS = 30,
  GridiconTypeShare = 31,
  GridiconTypeSearch = 32,
  GridiconTypeScheduled = 33,
  GridiconTypeRotate = 34,
  GridiconTypeResize = 35,
  GridiconTypeReply = 36,
  GridiconTypeRefund = 37,
  GridiconTypeRefresh = 38,
  GridiconTypeRedo = 39,
  GridiconTypeReblog = 40,
  GridiconTypeReaderFollowing = 41,
  GridiconTypeReaderFollow = 42,
  GridiconTypeReader = 43,
  GridiconTypeReadMore = 44,
  GridiconTypeQuote = 45,
  GridiconTypeProductVirtual = 46,
  GridiconTypeProductExternal = 47,
  GridiconTypeProductDownloadable = 48,
  GridiconTypeProduct = 49,
  GridiconTypePrint = 50,
  GridiconTypePosts = 51,
  GridiconTypePopout = 52,
  GridiconTypePlusSmall = 53,
  GridiconTypePlus = 54,
  GridiconTypePlugins = 55,
  GridiconTypePlay = 56,
  GridiconTypePlans = 57,
  GridiconTypePin = 58,
  GridiconTypePhone = 59,
  GridiconTypePencil = 60,
  GridiconTypePause = 61,
  GridiconTypePages = 62,
  GridiconTypeOffline = 63,
  GridiconTypeNoticeOutline = 64,
  GridiconTypeNotice = 65,
  GridiconTypeNotVisible = 66,
  GridiconTypeNextPage = 67,
  GridiconTypeMySitesHorizon = 68,
  GridiconTypeMySites = 69,
  GridiconTypeMultipleUsers = 70,
  GridiconTypeMoney = 71,
  GridiconTypeMinusSmall = 72,
  GridiconTypeMinus = 73,
  GridiconTypeMicrophone = 74,
  GridiconTypeMenus = 75,
  GridiconTypeMenu = 76,
  GridiconTypeMention = 77,
  GridiconTypeMail = 78,
  GridiconTypeLock = 79,
  GridiconTypeLocation = 80,
  GridiconTypeListUnordered = 81,
  GridiconTypeListOrdered = 82,
  GridiconTypeListOrderedRTL = 83,
  GridiconTypeListCheckmark = 84,
  GridiconTypeLinkBreak = 85,
  GridiconTypeLink = 86,
  GridiconTypeLayoutBlocks = 87,
  GridiconTypeLayout = 88,
  GridiconTypeItalic = 89,
  GridiconTypeInstitution = 90,
  GridiconTypeInk = 91,
  GridiconTypeInfoOutline = 92,
  GridiconTypeInfo = 93,
  GridiconTypeIndentRight = 94,
  GridiconTypeIndentLeft = 95,
  GridiconTypeImageRemove = 96,
  GridiconTypeImageMultiple = 97,
  GridiconTypeImage = 98,
  GridiconTypeHouse = 99,
  GridiconTypeHistory = 100,
  GridiconTypeHelpOutline = 101,
  GridiconTypeHelp = 102,
  GridiconTypeHeartOutline = 103,
  GridiconTypeHeart = 104,
  GridiconTypeHeadingH6 = 105,
  GridiconTypeHeadingH5 = 106,
  GridiconTypeHeadingH4 = 107,
  GridiconTypeHeadingH3 = 108,
  GridiconTypeHeadingH2 = 109,
  GridiconTypeHeadingH1 = 110,
  GridiconTypeHeading = 111,
  GridiconTypeGrid = 112,
  GridiconTypeGlobe = 113,
  GridiconTypeFullscreenExit = 114,
  GridiconTypeFullscreen = 115,
  GridiconTypeFolderMultiple = 116,
  GridiconTypeFolder = 117,
  GridiconTypeFlipVertical = 118,
  GridiconTypeFlipHorizontal = 119,
  GridiconTypeFlag = 120,
  GridiconTypeFilter = 121,
  GridiconTypeExternal = 122,
  GridiconTypeEllipsisCircle = 123,
  GridiconTypeEllipsis = 124,
  GridiconTypeDropdown = 125,
  GridiconTypeDomains = 126,
  GridiconTypeCustomize = 127,
  GridiconTypeCustomPostType = 128,
  GridiconTypeCrossSmall = 129,
  GridiconTypeCrossCircle = 130,
  GridiconTypeCross = 131,
  GridiconTypeCrop = 132,
  GridiconTypeCreditCard = 133,
  GridiconTypeCreate = 134,
  GridiconTypeCoupon = 135,
  GridiconTypeComputer = 136,
  GridiconTypeComment = 137,
  GridiconTypeCog = 138,
  GridiconTypeCode = 139,
  GridiconTypeCloudUpload = 140,
  GridiconTypeCloudOutline = 141,
  GridiconTypeCloudDownload = 142,
  GridiconTypeCloud = 143,
  GridiconTypeClipboard = 144,
  GridiconTypeClearFormatting = 145,
  GridiconTypeChevronUp = 146,
  GridiconTypeChevronRight = 147,
  GridiconTypeChevronLeft = 148,
  GridiconTypeChevronDown = 149,
  GridiconTypeCheckmarkCircle = 150,
  GridiconTypeCheckmark = 151,
  GridiconTypeChat = 152,
  GridiconTypeCart = 153,
  GridiconTypeCaption = 154,
  GridiconTypeCamera = 155,
  GridiconTypeCalendar = 156,
  GridiconTypeBug = 157,
  GridiconTypeBriefcase = 158,
  GridiconTypeBookmarkOutline = 159,
  GridiconTypeBookmark = 160,
  GridiconTypeBook = 161,
  GridiconTypeBold = 162,
  GridiconTypeBlock = 163,
  GridiconTypeBell = 164,
  GridiconTypeAudio = 165,
  GridiconTypeAttachment = 166,
  GridiconTypeAside = 167,
  GridiconTypeArrowUp = 168,
  GridiconTypeArrowRight = 169,
  GridiconTypeArrowLeft = 170,
  GridiconTypeArrowDown = 171,
  GridiconTypeAlignRight = 172,
  GridiconTypeAlignLeft = 173,
  GridiconTypeAlignJustify = 174,
  GridiconTypeAlignImageRight = 175,
  GridiconTypeAlignImageNone = 176,
  GridiconTypeAlignImageLeft = 177,
  GridiconTypeAlignImageCenter = 178,
  GridiconTypeAlignCenter = 179,
  GridiconTypeAddOutline = 180,
  GridiconTypeAddImage = 181,
  GridiconTypeAdd = 182,
};

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif

#endif
