/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.editor;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

@Kroll.module(name="TitaniumRichTextEditor", id="ti.editor")
public class TitaniumRichTextEditorModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "TitaniumRichTextEditorModule";
	private static final boolean DBG = TiConfig.LOGD;

	public TitaniumRichTextEditorModule()
	{
		super();
	}
}

