/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.editor;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;


@Kroll.module(name="TitaniumRichTextEditor", id="ti.editor")
public class TitaniumRichTextEditorModule extends KrollModule {

	public TitaniumRichTextEditorModule() {
		super();
	}
}

